# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# Renaming? Change the README badge.
name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Ensure that the two apps build, and SDK javadocs are OK.
      - name: Perform base checks
        run: ./gradlew BranchSearchDemo:assembleDebug DiscoLinkTester:assembleDebug BranchSearchSDK:javadoc
  ANDROID_EMULATOR_TESTS:
    name: Emulator Tests
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        EMULATOR_API: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
        include:
          - EMULATOR_API: 29
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 28
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 27
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 26
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 25
            EMULATOR_ARCH: x86
          - EMULATOR_API: 24
            EMULATOR_ARCH: x86
          - EMULATOR_API: 23
            EMULATOR_ARCH: x86
          - EMULATOR_API: 22
            EMULATOR_ARCH: x86
          - EMULATOR_API: 21
            EMULATOR_ARCH: x86
          - EMULATOR_API: 20
            EMULATOR_ARCH: x86
          - EMULATOR_API: 19
            EMULATOR_ARCH: x86
          - EMULATOR_API: 18
            EMULATOR_ARCH: x86
          - EMULATOR_API: 17
            EMULATOR_ARCH: x86
          - EMULATOR_API: 16
            EMULATOR_ARCH: x86
          - EMULATOR_API: 15
            EMULATOR_ARCH: x86
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Execute emulator tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.EMULATOR_API }}
          arch: ${{ matrix.EMULATOR_ARCH }}
          disable-animations: true
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back none -camera-front none -gpu swiftshader_indirect
          script: ./gradlew BranchSearchSDK:connectedCheck
      - name: Upload emulator tests artifact
        uses: actions/upload-artifact@v1
        with:
          name: emulator_tests_${{ matrix.EMULATOR_API }}
          path: ./BranchSearchSDK/build/outputs/code_coverage/debugAndroidTest/connected
